# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'navigation exp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for navigation exp
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
pod 'Firebase'


end
